# Generated by Django 6.0.1 on 2026-02-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=100)),
                ('bookDesc', models.CharField(max_length=255)),
                ('bookAuthor', models.CharField(max_length=50)),
                ('bookPoster', models.CharField()),
                ('bookPrice', models.IntegerField()),
            ],
        ),
    ]
